# /apps/blog.silarhi.fr/docker-compose.yml
version: '3'

services:

  database:
    image: mariadb
    container_name: ${NAME}_db
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: "${MYSQL_DATABASE}"
      MARIADB_USER: "${MYSQL_USERNAME}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}" 
    networks:
      - lan
    volumes: 
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin 
    container_name: ${NAME}_pma
    restart: unless-stopped
    environment: 
      PMA_ABSOLUTE_URI: https://${NAME}.jrcandev.netlib.re/phpmyadmin
      PMA_HOST: ${NAME}_db
      UPLOAD_LIMIT: 128M
    labels:
      - traefik.enable=true  
      - traefik.http.routers.pma_${NAME}.entrypoints=websecure
      - traefik.http.routers.pma_${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`) && PathPrefix(`/phpmyadmin/`)
      - traefik.http.middlewares.pmapathstrip_${NAME}.stripprefix.prefixes=/phpmyadmin
      - traefik.http.routers.pma_${NAME}.middlewares=pmapathstrip_${NAME}@docker
      - traefik.http.routers.pma_${NAME}.tls=true
      - traefik.http.routers.pma_${NAME}.tls.certresolver=myresolver
    volumes:
        - /sessions
    networks:
        - web      
        - lan
  app:
    #image: php:8.2-apache
    container_name: ${NAME}
    build: .
    networks:
        - lan
        - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.entryPoints=websecure 
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`)
      - traefik.http.routers.${NAME}.tls=true  
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver
          
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      container__name: ${NAME}
      database__client: mysql
      database__connection__host: ${NAME}_db
      database__connection__user: "${MYSQL_USERNAME}"
      database__connection__password: "${MYSQL_PASSWORD}"
      database__connection__database: "${MYSQL_DATABASE}"
    volumes:
      - ./src:/var/www/html 

volumes:
  db:

networks:
  web:
    external: true
  lan:
    external: false
    name: lan_${NAME}    
